### ISSUE TITLE
Supporting g105

### ISSUE THREAD

**Issue by Ivan-SB** [makei/libg15-gnome15#1]
Hi,

I just bought a g105 and tried to make it work with g105daemon hoping it was not that different from g110.
So I simply added it in the g15_devices[] array the signature for g105 but it didn't work.
It exits here:
g15_log(stderr,G15_LOG_INFO,"Error setting the configuration, this is fatal. Returned %d\n", ret);
with (-16).

Adding G15_DEVICE_IS_SHARED g15daemon run but my keyboard freeze.

Unfortunately I have no knowledge of usb internals, but my hope is that with a little bit of help I could grasp enough to be able to add support for my keyboard too.

thanks for any help

**Comment by makei** [comment]
I am sorry, but I am not supporting this code. I only cloned russo79 repos and after his page went down I put code on github so it won't get lost.
